#### Models ####
{% for i in range(20) %}
uci_wine_quality_cnf_{{i}}:
  model_params:
    # loss_function: "MultiRMSE"
    # embedding_dim: 40
    num_blocks: 3
    device: "cpu"

  model_hyperparams:
    embedding_dim: [0]
    hidden_dims: [[32,32], [80, 40]]
    # num_layers: [6]
    # depth: [2, 4]
    # tree_output_dim: [1]
    # num_trees: [100]
    # flow_hidden_dims: [[32,32], [16,16,16], [32, 32, 32], [64,64,32]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}

# kedro run --pipeline=uci_wine_quality_cnf && kedro run --pipeline=uci_concrete_cnf

{% for i in range(20) %}
uci_concrete_cnf_{{i}}:
  model_params:
    # loss_function: "MultiRMSE"
    num_blocks: 3
    device: "cpu"

  model_hyperparams:
    embedding_dim: [0]
    hidden_dims: [[32,32], [80, 40]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_concrete_cnf

{% for i in range(20) %}
uci_energy_cnf_{{i}}:
  model_params:
    num_blocks: 3
    # loss_function: "MultiRMSE"
    device: "cpu"

  model_hyperparams:
    embedding_dim: [0]
    hidden_dims: [[80, 40], [80, 80, 40]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 8
{% endfor %}
# kedro run --pipeline=uci_energy_cnf && kedro run --pipeline=uci_kin8nm_cnf

{% for i in range(20) %}
uci_kin8nm_cnf_{{i}}:
  model_params:
    num_blocks: 3
    device: "cpu"

  model_hyperparams:
    embedding_dim: [0]
    hidden_dims: [[80, 40], [80, 80, 40]]
  #### Training ####

  n_epochs: 100
  split_size: 0.8
  random_seed: 42
  batch_size: 1024
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
# kedro run --pipeline=uci_kin8nm_cnf

{% for i in range(20) %}
uci_naval_cnf_{{i}}:
  model_params:
    num_blocks: 3
    device: "cpu"
# 
  model_hyperparams:
    embedding_dim: [0]
    hidden_dims: [[80, 40], [100, 100, 50]]
  #### Training ####

  n_epochs: 200
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 8
{% endfor %}
# kedro run --pipeline=uci_naval_cnf

{% for i in range(20) %}
uci_power_plant_cnf_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [50, 100] # 50, 
    flow_hidden_dims: [[16,16], [16, 16, 16]] # [64,64,64], [32, 32, 32], [32,32]
  #### Training ####

  n_epochs: 200
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 8
{% endfor %}
# kedro run --pipeline=uci_power_plant_cnf



{% for i in range(20) %}
uci_protein_cnf_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [300] # 50, 
    flow_hidden_dims: [[32, 32, 32], [16, 16, 16]] # [64,64,32], 
  #### Training ####

  n_epochs: 75
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
# kedro run --pipeline=uci_protein_cnf