
momogp_energy_nodeflow:
  model_hyperparams:
    num_layers: [1,6]
    depth: [1, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 3]
  #### Training ####

  n_epochs: 100
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 100
  sample_batch_size: 32


momogp_parkinsons_nodeflow:
  model_hyperparams:
    num_layers: [1,6]
    depth: [2, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 3]
  #### Training ####

  n_epochs: 500
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 100
  sample_batch_size: 32


momogp_scm20d_nodeflow:
  model_hyperparams:
    num_layers: [1,6]
    depth: [2, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 3]
  #### Training ####

  n_epochs: 300
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 100
  sample_batch_size: 32


momogp_wind_nodeflow:
  model_hyperparams:
    num_layers: [1,6]
    depth: [2, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 3]
  #### Training ####

  n_epochs: 200
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 100
  sample_batch_size: 32


momogp_usflight_nodeflow:
  model_hyperparams:
    num_layers: [1,3]
    depth: [2, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 10
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 100
  sample_batch_size: 32
