base_tree_params:
  criterion: "friedman_mse"
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  splitter: "best"

base_tree_hyperparams:
  max_depth: [3, 5]

ngboost_params:
  learning_rate: 0.01

ngboost_hyperparams:
  n_estimators: [100, 300, 500, 1000]

