#### Models ####
{% for i in range(20) %}
uci_wine_quality_red_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,3]
    depth: [2, 5]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 400
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_concrete_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,8]
    depth: [3,5]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 400
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_energy_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,8]
    depth: [3,5]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 400
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_naval_propulsion_plant_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [4,6]
    depth: [4,5]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 300
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_power_plant_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [3,5]
    depth: [3,4]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 200
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_kin8nm_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [4,7]
    depth: [3,5]
    tree_output_dim: [1,1]
    num_trees: [200, 500, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 60
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_protein_tertiary_structure_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [3,6]
    depth: [3,4]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 100
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_yacht_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1, 3]
    depth: [1,2]
    tree_output_dim: [1,1]
    num_trees: [100, 500, 100] 
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 400
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 1024
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}

{% for i in range(20) %}
uci_year_prediction_msd_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [6, 6]
    depth: [4, 4]
    tree_output_dim: [1, 1]
    num_trees: [300, 400, 100] 
    flow_hidden_dims_size: [8,16,32]
    flow_hidden_dims_shape: [2, 2]
  #### Training ####

  n_epochs: 10
  patience: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 3048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
