#### Models ####

model_params:
  num_layers: 6
  # loss_function: "MultiRMSE"
  # device: "mps"

model_hyperparams:
  depth: [1] #, 3, 6]
  num_trees: [100] #, 300]
#### Training ####

n_epochs: 5
# split_size: 0.8
batch_size: 1024
# num_samples: 1000
