#### Models ####
{% for i in range(20) %}
uci_wine_quality_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,8]
    depth: [3, 6]
    tree_output_dim: [1,3]
    num_trees: [50, 600, 50]
    flow_hidden_dims: [[16,16], [32,32]]
  #### Training ####

  n_epochs: 400
  patience: 30
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}

# kedro run --pipeline=uci_wine_quality_nodeflow

{% for i in range(20) %}
uci_concrete_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [4,12]
    depth: [4,7]
    tree_output_dim: [1,1]
    num_trees: [100, 600, 100]
    flow_hidden_dims: [[8,8], [16,16], [32,32]]
  #### Training ####

  n_epochs: 400
  patience: 40
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 1
{% endfor %}
# kedro run --pipeline=uci_concrete_nodeflow

{% for i in range(20) %}
uci_energy_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,11]
    depth: [1,6]
    tree_output_dim: [1,3]
    num_trees: [50, 600, 50]
    flow_hidden_dims: [[4,4], [8,8], [16,16], [32,32]]
  #### Training ####

  n_epochs: 400
  patience: 40
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_energy_nodeflow

{% for i in range(20) %}
uci_naval_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,11]
    depth: [2,6]
    tree_output_dim: [1,3]
    num_trees: [100, 600, 100]
    flow_hidden_dims: [[16,16], [32,32], [16, 16, 16]] # [64,64,64], [32, 32, 32]
  #### Training ####

  n_epochs: 300
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 64
{% endfor %}
# kedro run --pipeline=uci_naval_nodeflow

{% for i in range(20) %}
uci_power_plant_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,11]
    depth: [1,6]
    tree_output_dim: [1,2]
    num_trees: [50, 600, 50]
    flow_hidden_dims: [[16,16], [16, 16, 16]] # [64,64,64], [32, 32, 32], [32,32]
  #### Training ####

  n_epochs: 200
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_power_plant_nodeflow

{% for i in range(20) %}
uci_kin8nm_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,11]
    depth: [1,6]
    tree_output_dim: [1,2]
    num_trees: [100, 600, 100]
    flow_hidden_dims: [[64,64,32], [32, 32, 32], [32,32], [16, 16, 16]] # 
  #### Training ####

  n_epochs: 60
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_kin8nm_nodeflow

{% for i in range(20) %}
uci_protein_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1,11]
    depth: [1,6]
    tree_output_dim: [1,2]
    num_trees: [100, 600, 100]
    flow_hidden_dims: [[32, 32, 32], [16, 16, 16], [64,64,32]]
  #### Training ####

  n_epochs: 100
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_protein_nodeflow

{% for i in range(20) %}
uci_yacht_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [1, 11]
    depth: [1,10]
    tree_output_dim: [1,3]
    num_trees: [50, 500, 25] 
    flow_hidden_dims: [[100, 100, 50], [200, 100, 100, 50], [32, 32, 32], [16, 16, 16], [32,32], [16,16]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 1024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_yacht_nodeflow

{% for i in range(20) %}
uci_year_prediction_msd_nodeflow_{{i}}:
  model_hyperparams:
    num_layers: [6]
    depth: [4, 2]
    tree_output_dim: [1]
    num_trees: [300, 100, 50] 
    flow_hidden_dims: [[32, 32, 32], [16, 16, 16], [32,32]]
  #### Training ####

  n_epochs: 10
  split_size: 0.8
  random_seed: 42
  batch_size: 2048
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
# kedro run --pipeline=uci_year_prediction_msd_nodeflow