#### Models ####
{% for i in range(20) %}
uci_wine_quality_nodeflow_{{i}}:
  model_params:
    # loss_function: "MultiRMSE"
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [2, 4]
    tree_output_dim: [1]
    num_trees: [100]
    flow_hidden_dims: [[32,32], [16,16,16], [32, 32, 32], [64,64,32]]
  #### Training ####

  n_epochs: 300
  split_size: 0.8
  random_seed: 42
  batch_size: 1024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}

# kedro run --pipeline=uci_wine_quality_nodeflow && kedro run --pipeline=uci_concrete_nodeflow

{% for i in range(20) %}
uci_concrete_nodeflow_{{i}}:
  model_params:
    # loss_function: "MultiRMSE"
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [3]
    tree_output_dim: [1]
    num_trees: [500, 300, 100]
    flow_hidden_dims: [[32,32], [16, 16, 16], [32, 32, 32], [64,64,32]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_concrete_nodeflow

{% for i in range(20) %}
uci_energy_nodeflow_{{i}}:
  model_params:
    num_layers: 6
    depth: 3
    # loss_function: "MultiRMSE"
    device: "cuda"

  model_hyperparams:
    tree_output_dim: [1]
    num_trees: [50, 100] #, 300]
    flow_hidden_dims: [[16,16], [32,32], [16, 16, 16], [32, 32, 32]]
  #### Training ####

  n_epochs: 400
  split_size: 0.8
  random_seed: 42
  batch_size: 2024
  num_samples: 1000
  sample_batch_size: 32
{% endfor %}
# kedro run --pipeline=uci_energy_nodeflow

{% for i in range(20) %}
uci_naval_nodeflow_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [50, 100] #, 300]
    flow_hidden_dims: [[16,16], [32,32], [16, 16, 16]] # [64,64,64], [32, 32, 32]
  #### Training ####

  n_epochs: 300
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 8
{% endfor %}
# kedro run --pipeline=uci_naval_nodeflow

{% for i in range(20) %}
uci_power_plant_nodeflow_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [50, 100] # 50, 
    flow_hidden_dims: [[16,16], [16, 16, 16]] # [64,64,64], [32, 32, 32], [32,32]
  #### Training ####

  n_epochs: 200
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 8
{% endfor %}
# kedro run --pipeline=uci_power_plant_nodeflow

{% for i in range(20) %}
uci_kin8nm_nodeflow_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [500, 300, 100] # 50, 
    flow_hidden_dims: [[64,64,32], [32, 32, 32], [32,32], [16, 16, 16]] # 
  #### Training ####

  n_epochs: 50
  split_size: 0.8
  random_seed: 42
  batch_size: 1024
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
# kedro run --pipeline=uci_kin8nm_nodeflow

{% for i in range(20) %}
uci_protein_nodeflow_{{i}}:
  model_params:
    device: "cuda"

  model_hyperparams:
    num_layers: [6]
    depth: [4]
    tree_output_dim: [1]
    num_trees: [300] # 50, 
    flow_hidden_dims: [[32, 32, 32], [16, 16, 16]] # [64,64,32], 
  #### Training ####

  n_epochs: 75
  split_size: 0.8
  random_seed: 42
  batch_size: 4096
  num_samples: 1000
  sample_batch_size: 4
{% endfor %}
# kedro run --pipeline=uci_protein_nodeflow