#### Models ####

flow_params:
  # input_dim: 1
  input_dim: 2

flow_hyperparams:
  context_dim: [50, 100]
  hidden_dims: [[50, 50]]
  num_blocks: [1]

tree_params:
  # loss_function: "RMSEWithUncertainty"
  loss_function: "MultiRMSE"
  silent: True

tree_hyperparams:
  depth: [1]
  num_trees: [300, 500, 750]

tree_model_type: "CatBoostPriorNormal"
#### Training ####

n_epochs: 30
batch_size: 128
num_samples: 200