#### Models ####

flow_params:
  input_dim: 1
  # input_dim: 2

tree_params:
  loss_function: "RMSEWithUncertainty"
  # loss_function: "MultiRMSE"
  silent: True

#### Training ####
split_size: 0.8
n_epochs: 200
batch_size: 512
num_samples: 200
random_seed: 42

tree_model_type: "CatBoostPriorNormal"
