#### Models ####

flow_params:
  input_dim: 1

tree_params:
  loss_function: "RMSEWithUncertainty"
  silent: True

#### Training ####
split_size: 0.8
n_epochs: 200
batch_size: 512
num_samples: 100
random_seed: 42

tree_model_type: "CatBoostPriorNormal"
